const mongoose = require('mongoose')

const tabela = new mongoose.Schema({
    Codigo_da_oportunidade: Number,
    Classificacao_da_Oportunidade: String,
    Data_de_criacao: String,
    Faixa_de_Faturamento_Agregado: String,
    Data_Real_de_Encerramento_da_Opp2: String,
    id_fechou: Number,
    numero_relacionamentos: Number,
    numero_relacionamentos_convertidos: Number,
    intervalo_tempo: Number,
    ano: Number,
    Valor_corrigido2: Number,
    Forma_de_Contratacao_Agregado: String,
    Concorrentes: Number,
    n_solucoes: Number,
    Software: Number,
    Comissão_sobre_Parceiros: Number,
    Cybersecurity: Number,
    Desdobramento_de_metas: Number,
    ESG: Number,
    Equilíbrio_fiscal: Number,
    Skill_dev: Number,
    Gestão_Estratégica: Number,
    Gestão_da_Educação: Number,
    Gestão_da_Operação: Number,
    Gestão_da_Receita: Number,
    Gestão_da_Saúde: Number,
    Gestão_da_Segurança_Pública: Number,
    Gestão_da_Segurança_Viária: Number,
    Gestão_de_Gastos: Number,
    Gestão_de_operações_projetizadas: Number,
    Gestão_de_pessoas: Number,
    Processes_Excellence: Number,
    Produtos_digitais: Number,
    S_amp_OP_S_amp_OE: Number,
    Transformação_Digital: Number,
    Treinamentos: Number,
    Roadmap: Number,
    Segmentacao: Number,
    Carteira_Nova: String,
    Segmento_Agregado2: String,
    Total_HH: Number,
    Custo_Total: Number,
    Margem_Total: Number,
    ID_cliente: Number
});